title: Trials and Tribulations
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Swag
color:
  saturation: 0.9655436694156379
  brandStrength: 1
  lightness: 0.2347864382900298
  brandColors:
    - '#e3ded3'
    - '#ccc1ae'
    - '#937d61'
    - '#453421'
    - '#725d43'
  rhythmicContrast: 0.5776149409357458
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: Experiment
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.42548
layout_spectrum: 0.9713262
