name: Trials and Tribulations
favicon: null
layout_spectrum: 0.93081
typography_spectrum: 0.34358
title: Trials and Tribulations
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Swag
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9b649'
    - '#cf9331'
    - '#4c2013'
    - '#dd6028'
    - '#9a6c39'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
