name: Experiment
favicon: null
layout_spectrum: 0.78871
typography_spectrum: 0.42548
title: Trials and Tribulations
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Swag
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3ded3'
    - '#ccc1ae'
    - '#937d61'
    - '#453421'
    - '#725d43'
  brandStrength: 0.625
  lightness: 0.2347864382900298
  saturation: 0.9655436694156379
  rhythmicContrast: 0.5776149409357458
purpose: []
